apiVersion: apps/v1
kind: Deployment
metadata:
    name: front-end-deployment-dev
    namespace: dev
spec:
    replicas: 1 # minimum num of replicas before HPA is activated
    selector:
        matchLabels:
            app: front-end-app
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: front-end-app
        spec:
            containers:
                - image: front-end
                  imagePullPolicy: Never
                  name: front-end-container
                  ports:
                      - containerPort: 3000
                  resources:
                      requests:
                          memory: "150Mi" # Request 256MB of memory
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      limits:
                          memory: "200Mi" # Limit memory to 512MB
                          cpu: "200m" # Limit CPU to 0.2 CPU (200 milliCPU)
            restartPolicy: Always
status: {}
