apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb-statefulset-dev # The name of the StatefulSet
    namespace: dev # The namespace where the StatefulSet will be created

spec:
    replicas: 3 # Number of replica pods to create
    serviceName: mongodb-headless # A headless service for DNS-based discovery
    selector:
        matchLabels:
            app: mongodb # Select pods with the label "app: mongodb"
    updateStrategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: mongodb # Labels for pods created by the StatefulSet

        spec:
            containers:
                - name: mongodb # Name of the container
                  image: mongo:6.0 # Docker image for the MongoDB container
                  ports:
                      - containerPort: 27017 # Port to expose

            volumes:
                - name: mongodb-volume-data
                  persistentVolumeClaim:
                      claimName: mongodb-data
