apiVersion: apps/v1
kind: Deployment
metadata:
    name: question-service-deployment-dev
    namespace: dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: question-service-api
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: question-service-api
        spec:
            containers:
                - env:
                      - name: MONGODB_URI
                        value: mongodb://mongodb-headless.dev.svc.cluster.local:27017/question-service-api
                      - name: PORT_NUMBER
                        value: "8080"
                  image: question-service
                  imagePullPolicy: Never
                  name: question-service-api
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          memory: "150Mi" # Request 256MB of memory
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      limits:
                          memory: "200Mi" # Limit memory to 512MB
                          cpu: "200m" # Limit CPU to 0.2 CPU (200 milliCPU)
            restartPolicy: Always
status: {}
