apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: front-end-hpa-dev # Name of the HPA object
    namespace: dev
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: front-end-deployment-dev # Target Deployment for autoscaling
    minReplicas: 1 # Minimum number of pod replicas to maintain
    maxReplicas: 6 # Maximum number of pod replicas to scale up to
    metrics:
        - type: Pods # Metric type, in this case, resource utilization
          pods:
              metric:
                  name: cpu
              target:
                  type: Utilization
                  averageValue: "100m"
    behavior:
        scaleDown:
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 300
