apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: prometheus-data
    namespace: dev
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}