apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: front-end-hpa-prod # Name of the HPA object
    namespace: prod
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: front-end-deployment-prod # Target Deployment for autoscaling
    minReplicas: 1 # Minimum number of pod replicas to maintain
    maxReplicas: 6 # Maximum number of pod replicas to scale up to
    metrics:
        - type: Resource # Metric type, in this case, resource utilization
          resource:
              name: cpu # Resource metric to monitor (CPU in this case)
              target:
                  type: Utilization
                  averageUtilization: 10
    behavior:
        scaleDown:
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 300
