# For local development purposes only

version: '3'

services:
  question-service:
    container_name: question-service
    build:
      context: ./services/question-service
      target: base
    volumes:
      - ./services/question-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/question-service-api
      - PORT_NUMBER=8080
    ports:
      - "8080:8080"
    command: npm run start:dev
  
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - /data/db
    ports:
      - "27017:27017"
