# For local development purposes only

version: "3"

services:
    front-end:
        container_name: front-end
        build:
            context: ./front-end/peer-prep
        ports:
            - 3000:3000

    question-service:
        container_name: question-service
        build:
            context: ./services/question-service
            target: dev
            dockerfile: Dockerfile.dev
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/question-service-api
            - PORT_NUMBER=8080
        ports:
            - 8080:8080
        depends_on:
            - mongodb
        volumes:
            - ./services/question-service:/app

    mongodb:
        container_name: mongodb
        image: mongo:6.0
        volumes:
            - db-data:/data/db
        ports:
            - 27017:27017

    profile-service:
        container_name: profile-service
        build:
            context: ./services/profile-service
        ports:
            - 3100:3100
        volumes:
            - ./services/profile-service:/usr/src/app

volumes:
    db-data:
