apiVersion: v1
kind: Service
metadata:
    name: matching-service-service-dev
    namespace: dev
spec:
    selector:
        app: matching-service-api
    ports:
        - name: "8000"
          port: 8000
          targetPort: 8000
    type: NodePort # Use NodePort for localtesting / port forwarding
status:
    loadBalancer: {}
