apiVersion: v1
kind: Service
metadata:
    name: profile-service-service-dev
    namespace: dev
spec:
    selector:
        app: profile-service-api # Select pods with the label 'app: my-app' to include in the Service
    ports:
        - name: "3100"
          port: 3100
          targetPort: 3100
    type: NodePort # Use NodePort for localtesting / port forwarding
status:
    loadBalancer: {}
