apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-service-dev
    namespace: dev
spec:
    selector:
        app: rabbitmq
    ports:
        - name: "5672"
          port: 5672
          targetPort: 5672
        - name: "15672"
          port: 15672
          targetPort: 15672
    type: NodePort # Use NodePort for localtesting / port forwarding
status:
    loadBalancer: {}
