apiVersion: v1
kind: Service
metadata:
    name: front-end-service-prod # Name of the Service
    namespace: prod
spec:
    selector:
        app: front-end-app # Select pods with the label 'app: my-app' to include in the Service
    ports:
        - name: "front-end-port"
          port: 3000
          targetPort: 3000
    type: ClusterIP # Service type
status:
    loadBalancer: {}
