apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"3000":"k8s1-632f34ab-default-front-end-deployment-service-300-2a24e59e"},"zones":["asia-southeast1-a","asia-southeast1-c"]}'
  creationTimestamp: "2023-11-11T20:13:29Z"
  labels:
    app: front-end-app
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":3000,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":3000,"protocol":"UDP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2023-11-11T20:13:29Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cloud.google.com/neg-status: {}
    manager: glbc
    operation: Update
    subresource: status
    time: "2023-11-12T16:59:16Z"
  name: front-end-deployment-service
  namespace: default
  resourceVersion: "1384110"
  uid: 4340a607-beff-48b1-843d-05f139c5e78c
spec:
  clusterIP: 34.118.233.23
  clusterIPs:
  - 34.118.233.23
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 3000-to-3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: 3000-to-3000-udp
    port: 3000
    protocol: UDP
    targetPort: 3000
  selector:
    app: front-end-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
