apiVersion: v1
kind: Service
metadata:
    name: matching-service-db-headless
    namespace: prod
spec:
    clusterIP: None # This makes it a headless service
    selector:
        app: matching-service-db # Select the pods by their labels
    ports:
        - protocol: TCP
          port: 5432 # Port used for Postgres
