apiVersion: v1
kind: Service
metadata:
    name: question-service-service-prod
    namespace: prod
spec:
    selector:
        app: question-service-api
    ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
    type: NodePort # Use NodePort for localtesting / port forwarding
status:
    loadBalancer: {}
