apiVersion: v1
kind: Service
metadata:
  name: question-service-service-dev
  namespace: dev
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: question-service
status:
  loadBalancer: {}
