apiVersion: v1
kind: ConfigMap
metadata:
    name: matching-service-config-prod
    namespace: prod
data:
    PORT_NUMBER: "8000"
    AMQP_URL: amqp://rabbitmq-service-prod.prod.svc.cluster.local:5672
