apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-prod
  namespace: prod
data:
  prometheus-config.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      retention: "12h"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
