# For local development purposes only

version: "3.4"


services:
    # judge0:
    #     image: judge0/judge0:latest
    #     ports:
    #         - "8081:80"
    #     environment:
    #         - JUDGE0_API_DOMAIN=your-judge0-domain
    #         - JUDGE0_USE_REDIS=false
    #         - JUDGE0_STORAGE_PATH=/sandbox

    front-end:
        container_name: front-end
        image: front-end
        build:
            context: ../../../front-end/peer-prep
        environment:
            REACT_APP_ENVIRONMENT: "localhost"
        ports:
            - 3000:3000
        networks:
            - localNetwork

    question-service:
        container_name: question-service
        image: question-service
        ports:
            - 8080:8080
        build:
            context: ../../../services/question-service
            target: build
        command: ["npm", "run", "dev"]
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/question-service-api
            - PORT_NUMBER=8080
        depends_on:
            - mongodb
        # volumes:
        #     - ./services/question-service:/app
        networks:
            - localNetwork

    mongodb:
        container_name: mongodb
        image: mongo:6.0
        volumes:
            - db-data:/data/db
        ports:
            - 27017:27017
        networks:
            - localNetwork

    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data
        ports:
            - 5433:5432
        networks:
            - localNetwork

    profile-service:
        container_name: profile-service
        image: profile-service
        build:
            context: ../../../services/profile-service
        ports:
            - 3100:3100
        environment:
            - POSTGRES_HOST=host.docker.internal
            - POSTGRES_PORT=5433
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=example
            - POSTGRES_DATABASE=postgres
        # volumes:
        #     - ./services/profile-service:/usr/src/app
        networks:
            - localNetwork

    matching-service:
        container_name: matching-service
        build:
            context: ../../../services/matching-service
            target: build
        command: ["npm", "run", "dev"]
        environment:
            - PORT_NUMBER=8000
            - AMQP_URL=amqp://rabbitmq:5672
        ports:
            - 8000:8000
        depends_on:
            - rabbitmq
            - matching-worker-service
        links:
            - rabbitmq
            - matching-worker-service
        # volumes:
        #     - ./services/matching-service:/app
        networks:
            - localNetwork

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:15672"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 40s
        networks:
            - localNetwork

    matching-worker-service:
        container_name: matching-worker-service
        build:
            context: ../../../services/matching-worker-service
            target: build
        command: ["npm", "run", "dev"]
        environment:
            - AMQP_URL=amqp://rabbitmq:5672
            - DATABASE_URL=postgresql://root:secret@matching-service-db:5432/matching_service?schema=public
        depends_on:
            - rabbitmq
            - matching-service-db
        links:
            - rabbitmq
            - matching-service-db
        restart: on-failure
        # volumes:
        #     - ./services/matching-worker-service:/app
        networks:
            - localNetwork

    matching-service-db:
        image: postgres:16-alpine
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=matching_service
        ports:
            - 5432:5432
        volumes:
            - matching-service-data:/var/lib/postgresql/data
        networks:
        - localNetwork

    collaboration-service:
        container_name: collaboration-service
        image: collaboration-service
        build:
            context: ../../../services/collaboration-service
        ports:
            - 8576:8576
        networks:
            - localNetwork

networks:       
    localNetwork:
        driver: bridge


volumes:
    db-data:
    matching-service-data:
