FROM node:18-alpine as base
WORKDIR /usr/src/app
EXPOSE 8080

FROM base as dev
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --include=dev
USER node
COPY . .
CMD ["npm", "run", "start:dev"]
