apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Deployments
  - ../dev/deployments/front-end-deployment-dev.yaml
  - ../dev/deployments/mongodb-statefulset-dev.yaml
  - ../dev/deployments/profile-service-deployment-dev.yaml
  - ../dev/deployments/question-service-deployment-dev.yaml

  # Ingresses
  - ../dev/ingresses/nginx-ingress-dev.yaml

  # Scalers
  - ../dev/scalers/horizontal/front-end-hpa-dev.yaml

  # Services
  - ../dev/services/front-end-service-dev.yaml
  - ../dev/services/mongodb-service-dev.yaml
  - ../dev/services/profile-service-service-dev.yaml
  - ../dev/services/question-service-service-dev.yaml

  # Volumes
  - ../dev/volumes/mongodb-pvc.yaml
