apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-end
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: front-end
    spec:
      containers:
        - image: front-end
          name: front-end
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
