apiVersion: apps/v1
kind: Deployment
metadata:
    name: front-end-deployment # Name of the Deployment
    namespace: testing
spec:
    replicas: 3 # Number of desired pod replicas
    selector:
        matchLabels:
            app: front-end-app # Select pods with the label 'app: my-app'
    strategy: {}
    template:
        metadata:
            labels:
                app: front-end-app # Apply the label 'app: my-app' to pods created by the Deployment
        spec:
            containers:
                - image: registry.gitlab.com/peerprepgroup51sem1y2023/docker/frontend:latest # Docker image to run in the container
                  name: front-end-container # Name of the container within the pod
                  ports:
                      - containerPort: 3000
                  resources: {}
            restartPolicy: Always
status: {}
