apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb-statefulset-dev # The name of the StatefulSet
    namespace: dev # The namespace where the StatefulSet will be created

spec:
    replicas: 3 # Number of replica pods to create
    serviceName: mongodb-headless # A headless service for DNS-based discovery

    selector:
        matchLabels:
            app: mongodb # Select pods with the label "app: mongodb"

    template:
        metadata:
            labels:
                app: mongodb # Labels for pods created by the StatefulSet

        spec:
            containers:
                - name: mongodb # Name of the container
                  image: mongo:6.0 # Docker image for the MongoDB container
                  ports:
                      - containerPort: 27017 # Port to expose

                  volumeMounts:
                      - name: mongodb-data # Name of the Persistent Volume Claim (PVC)
                        mountPath: /data/db # Mount path within the container

        volumeClaimTemplates:
            - metadata:
                  name: mongodb-data # Name of the Persistent Volume Claim (PVC) defined in mongodb-pvc.yaml
