apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: question-service
  name: question-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: question-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: question-service
    spec:
      containers:
        - env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/question-service-api
            - name: PORT_NUMBER
              value: "8080"
          image: question-service
          name: question-service
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app
              name: question-service-claim0
      restartPolicy: Always
      volumes:
        - name: question-service-claim0
          persistentVolumeClaim:
            claimName: question-service-claim0
status: {}
