apiVersion: apps/v1
kind: Deployment
metadata:
    name: front-end-deployment-prod
    namespace: prod
    annotations:
        keel.sh/policy: minor # <-- policy name according to https://semver.org/
        keel.sh/trigger: poll # <-- actively query registry, otherwise defaults to webhooks
spec:
    replicas: 1 # minimum num of replicas before HPA is activated
    selector:
        matchLabels:
            app: front-end-app
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: front-end-app
        spec:
            containers:
                - image: registry.gitlab.com/peerprepgroup51sem1y2023/docker/frontend:latest
                  name: front-end-container
                  ports:
                      - containerPort: 3000
                  resources:
                      requests:
                          memory: "100Mi" # Request 256MB of memory
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      limits:
                          memory: "100Mi" # Limit memory to 512MB
                          cpu: "100m" # Limit CPU to 0.2 CPU (200 milliCPU)
            restartPolicy: Always
status: {}
