apiVersion: apps/v1
kind: Deployment
metadata:
    name: keel-deployment
    namespace: prod
spec:
    replicas: 2
    selector:
        matchLabels:
            app: keel
    strategy: 
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: keel
        spec:
            containers:
                - name: keel
                  image: keelhq/keel
                  imagePullPolicy: IfNotPresent # Set your desired pull policy
                  resources:
                    limits:
                        memory: "128Mi" # Adjust resource limits as needed
                        cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                    requests:
                        memory: "64Mi"
                        cpu: "100m" # Request 0.1 CPU (100 milliCPU)