apiVersion: apps/v1
kind: Deployment
metadata:
    name: keel-deployment
    namespace: prod
spec:
    replicas: 1
    selector:
        matchLabels:
            app: keel
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: keel
        spec:
            containers:
                - name: keel
                  image: keelhq/keel
                  imagePullPolicy: IfNotPresent # Set your desired pull policy
                  resources:
                      limits:
                          memory: "100Mi" # Adjust resource limits as needed
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      requests:
                          memory: "100Mi"
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
