apiVersion: apps/v1
kind: Deployment
metadata:
    name: matching-service-deployment-prod # Name of the deployment
    namespace: prod # Namespace in which the deployment will be created
spec:
    # replicas: 1 # Number of desired replicas
    selector:
        matchLabels:
            app: matching-service-api # Label selector for the pods controlled by this deployment
    strategy:
        type: Recreate # Deployment strategy, which recreates all pods when updating
    dependsOn:

    template:
        metadata:
            labels:
                app: matching-service-api # Label for pods created by this template
        spec:
            containers:
                - name: matching-service-api # Name of the container
                  image: registry.gitlab.com/peerprepgroup51sem1y2023/docker/matching-service:latest
                  ports:
                      - containerPort: 8000 # Port on which the container listens
                  resources:
                      requests:
                          memory: "100Mi" # Request 256MB of memory
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      limits:
                          memory: "100Mi" # Limit memory to 512MB
                          cpu: "100m" # Limit CPU to 0.2 CPU (200 milliCPU)
                  env:
                      - name: PORT_NUMBER
                        valueFrom:
                            configMapKeyRef:
                                name: matching-service-config-prod
                                key: PORT_NUMBER
                      - name: AMQP_URL
                        valueFrom:
                            configMapKeyRef:
                                name: matching-service-config-prod
                                key: AMQP_URL
            # restartPolicy: "OnFailure" # Restart policy for the pods
status: {} # Empty status section
