apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb-statefulset-prod # The name of the StatefulSet
    namespace: prod # The namespace where the StatefulSet will be created

spec:
    replicas: 1 # Standalone mongodb database
    serviceName: mongodb-headless # A headless service for DNS-based discovery
    selector:
        matchLabels:
            app: mongodb # Select pods with the label "app: mongodb"
    updateStrategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: mongodb # Labels for pods created by the StatefulSet

        spec:
            containers:
                - name: mongodb # Name of the container
                  image: mongo:6.0 # Docker image for the MongoDB container
                  ports:
                      - containerPort: 27017 # Port to expose
                  resources:
                      requests:
                          memory: "100Mi" # Request 256MB of memory
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      limits:
                          memory: "100Mi" # Limit memory to 512MB
                          cpu: "100m" # Limit CPU to 0.2 CPU (200 milliCPU)
            volumes:
                - name: mongodb-volume-data
                  persistentVolumeClaim:
                      claimName: mongodb-pvc-prod
