apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: prometheus-deployment-prod
    namespace: prod
spec:
    serviceName: prometheus
    replicas: 1
    selector:
        matchLabels:
            app: prometheus
    template:
        metadata:
            labels:
                app: prometheus
        spec:
            containers:
                - name: prometheus
                  image: prom/prometheus:v2.33.1
                  ports:
                      - containerPort: 9090
                  resources:
                      requests:
                          memory: "100Mi" # Request 256MB of memory
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      limits:
                          memory: "100Mi" # Limit memory to 512MB
                          cpu: "100m" # Limit CPU to 0.2 CPU (200 milliCPU)
                  env:
                      - name: PROMETHEUS_CONFIG
                        value: |
                            global:
                                scrape_interval: 15s
                                evaluation_interval: 15s
                                retention: "12h"
                            scrape_configs:
                                - job_name: 'prometheus'
                                static_configs:
                                    - targets: ['localhost:9090']
            volumes:
                - name: prometheus-volume-data
                  persistentVolumeClaim:
                      claimName: prometheus-pvc-prod
