apiVersion: apps/v1
kind: Deployment
metadata:
    name: question-service-deployment-prod
    namespace: prod
    annotations:
        keel.sh/policy: minor # <-- policy name according to https://semver.org/
        keel.sh/trigger: poll # <-- actively query registry, otherwise defaults to webhooks
spec:
    replicas: 1
    selector:
        matchLabels:
            app: question-service-api
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: question-service-api
        spec:
            containers:
                - image: registry.gitlab.com/peerprepgroup51sem1y2023/docker/question-service:latest
                  name: question-service-api
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          memory: "100Mi" # Request 256MB of memory
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      limits:
                          memory: "100Mi" # Limit memory to 512MB
                          cpu: "100m" # Limit CPU to 0.2 CPU (200 milliCPU)
                  env:
                      - name: MONGODB_URI
                        valueFrom:
                            configMapKeyRef:
                                name: question-service-config-prod
                                key: MONGODB_URI
                      - name: PORT_NUMBER
                        valueFrom:
                            configMapKeyRef:
                                name: question-service-config-prod
                                key: PORT_NUMBER
            restartPolicy: Always
status: {}
