apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq-deployment-prod # Name of the deployment
    namespace: prod # Namespace in which the deployment will be created
spec:
    replicas: 1 # Number of desired replicas
    selector:
        matchLabels:
            app: rabbitmq # Label selector for the pods controlled by this deployment
    strategy:
        type: RollingUpdate # Deployment strategy, which recreates all pods when updating
    template:
        metadata:
            labels:
                app: rabbitmq # Label for pods created by this template
        spec:
            containers:
                - name: rabbitmq # Name of the container
                  image: rabbitmq # Docker image for the container
                  ports:
                      - containerPort: 5672 # Port on which the container listens
                      - containerPort: 15672
                  resources:
                      requests:
                          memory: "150Mi" # Request 256MB of memory
                          cpu: "100m" # Request 0.1 CPU (100 milliCPU)
                      limits:
                          memory: "200Mi" # Limit memory to 512MB
                          cpu: "200m" # Limit CPU to 0.2 CPU (200 milliCPU)
                  env:
                      - name: RABBITMQ_DEFAULT_USER
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-config-prod
                                key: RABBITMQ_DEFAULT_USER
                      - name: RABBITMQ_DEFAULT_PASS
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-config-prod
                                key: RABBITMQ_DEFAULT_PASS
            restartPolicy: Always # Restart policy for the pods
status: {} # Empty status section
