apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: matching-service-db-data
    namespace: prod
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 100Mi
status: {}
