apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv-prod
    namespace: prod
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: mongodb-storage-prod
    hostPath:
        path: "/storage/mongodb-data"
