name: Build and Push Question Service to Gitlab Container Registry

on:
  push:
    branches:
      - master # Adjust this to the branch you want to trigger the workflow on
    paths:
      - "services/question-service/**"
  workflow_run:
    workflows: ["ci.yml"] # Name of the CI workflow
    types:
      - completed
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitLab Container Registry
        run: docker login registry.gitlab.com -u ${{ secrets.GITLAB_USERNAME }} -p ${{ secrets.DOCKER }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: services/question-service
          file: ./services/question-service/Dockerfile
          push: true
          tags: registry.gitlab.com/peerprepgroup51sem1y2023/docker/question-service:latest
